### ISSUE TITLE
Jetty 11 support

### ISSUE THREAD

**Issue by spencergibb** [wiremock/wiremock#1760] opened 2022-01-04 17:50 UTC
Spring Framework 6 has [announced](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) a baseline to jakarta ee 9 (including javax -> jakarta packages). Any project that uses framework 6 or Spring Boot 3 will be incompatible with anything less than [jetty 11](https://www.eclipse.org/jetty/)

**Comment by wind57** [comment] 2022-01-07 11:35
it is also worth pointing out that this means java-17 and above _only_. I am not exactly sure if wiremock supports java-17 at the moment. I am still trying to figure out this...

**Comment by wind57** [comment] 2022-01-11 20:06
I thought I could just give a shot at this and upgrade to jetty-11. So far, this has not been easy. 

The first serious problem is `commons-fileupload` dependency, that still uses `javax` package. In their master branch they do not use that anymore, the problem is that this is not released (`commons-fileupload2`) yet, not are there any roadmaps on their github page. I build locally from their master branch and upgraded the dependency here, after which at least I can at least compile everything with jetty-11.

The second big problem is self-signed certificates (at least this is how I understand it). For example running some tests, I would get : 

```
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:267)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:208)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:414)
        .....
```

when issue-ing a `curl` (in debug mode). This is what I am struggling to fix, currently. 
Writing this note here, may be someone knows or could help with an advice...

**Comment by tomakehurst** [comment] 2022-01-11 20:13
@wind57 We can't just upgrade to Jetty 11 because (as you've pointed out) this would raise the minimum Java version to 11.

I think the correct near-term solution would be to start building an additional JAR artifact with a `-jre11` suffix that uses Jetty 11. Eventually (as with the JRE7 JAR), when Java 8 has fully faded from living memory, the `-jre11` will become the primary.

**Comment by tomakehurst** [comment] 2022-01-11 20:15
@wind57 re self-signed certificates - this is a JDK17 problem rather than Jetty. The current WireMock version doesn't support certificate signing at the moment and we're looking for a long term solution for that - #1706

**Comment by wind57** [comment] 2022-01-11 21:04
@tomakehurst thank you for your feedback. The `-jre11` (or whatever other meaningful qualifier) is exactly what I thought about, too. 

> when Java 8 has fully faded from living memory

For a lot of people, this is not going to be any time soon. This leaves wiremock (and a lot of other projects) in a delicate situation. You need to maintain at least two versions now and be able to back-port fixes and features, in possibly incompatible versions (you can't cherry pick that is) :( 

The self-signed certificates is indeed a much bigger problem. Spring is already committed to jetty-11, as announced, but lots of their projects have dependencies on wiremock, of course. I don't know what will happen, but keen to find out...

**Comment by spencergibb** [comment] 2022-01-11 21:16
btw, changing to `wiremock-jre8-standalone` fixed it for us in spring-cloud-k8s

**Comment by tomakehurst** [comment] 2022-01-12 10:26
The Spring Cloud Contract team have been using `wiremock-jre8-standalone` for a while and apparently that means they avoid the Jetty 11 problem.

**Comment by wind57** [comment] 2022-01-12 11:35
indeed! at least there is a clear workaround for the problem, thank you @tomakehurst and @spencergibb

**Comment by acogoluegnes** [comment] 2022-06-29 07:03
Jetty 9.4 is going [Community EOL](https://github.com/eclipse/jetty.project/issues/7958), so being able to use Jetty 11 seems appropriate now. Requiring Java 11 will be a problem for many users, so I'd suggest making the server support pluggable in Wiremock and/or using the appropriate version based on the JDK version.

**Comment by tomakehurst** [comment] 2022-07-26 15:52
We'll aim to add Jetty 11 support in the next release, probably under a new artifact name since it'll take us up to Java 11+.

**Comment by reta** [comment] 2022-08-31 00:43
@tomakehurst apologies, I don't see any progress on Jetty 11, appreciate any hints, or do you need a hand with that? Ready to step in, thank you.

**Comment by tomakehurst** [comment] 2022-09-01 15:01
Hi @reta, after some discussion with other contributors we think the way forward with this is to bump to a new major version of WireMock (3.x.x) and revert to using the default artifact ID again (dropping the `-jre8` builds from v3 onwards).

Making WireMock's faults and TLS features work with Jetty 11 is inevitably going to take some work, so if you feel like starting a pull request with the aim of getting all the tests passing with Jetty 11 that would be enormously helpful.

**Comment by vladimirfx** [comment] 2022-10-25 07:52
Because Jakarta migration requires massive changes IMO it makes sense to release the 3.0 milestone for integration testing. 2.x line may require parallel support for some reasonable time.

**Comment by alexhocks** [comment] 2022-12-02 13:03
First of all: Thank you for working on Jetty 11 support!

Is there any ETA for when we can expect a first WireMock 3.x.x build?
We are using WireMock for our testing and we are keen on upgrading to Sprint Boot 3.0 as soon as we can.

**Comment by ylacaute** [comment] 2022-12-24 14:17
@vladimirfx I don't get it, how do you use `standalone` version with Spring Boot 3 ?
I added this dependency :
```xml
		<dependency>
			<groupId>com.github.tomakehurst</groupId>
			<artifactId>wiremock-jre8-standalone</artifactId>
			<scope>test</scope>
		</dependency>
```
And use `wireMockServer.start()` manually but still have an error : `NoClassDefFoundError: javax/servlet/DispatcherType`

**Closed** 2022-12-30 18:24 UTC
