### ISSUE TITLE
jetty 12 / springboot 3.2  

### ISSUE THREAD

**Issue by GregoireW** [wiremock/wiremock#2395] opened 2023-09-26 08:38 UTC
### Proposal

As I'm creating a new small product I was evaluating springboot 3.2  and face an issue with wiremock as springboot3.2 will use jetty 12, and wiremock  jetty11.  

Some jetty artifacts and packages are moving which will make this change challenging on wiremock side. 

### Workaround

As a workaround, we can replace the wiremock package by the standalone one ( **org.wiremock:wiremock-standalone** ) so this is not an absolute blocker.

### References

https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12-maven-artifacts

**Comment by mschout** [comment] 2023-11-24 17:39
Spring boot 3.2.0 is out now FYI.  I can confirm wiremock is not working.

Getting errors like this during tests:

java.lang.IncompatibleClassChangeError: class org.eclipse.jetty.http2.server.HttpChannelOverHTTP2 has interface org.eclipse.jetty.server.HttpChannel as super class

Presumably due to jetty version mismatch.

**Comment by Wassmd** [comment] 2023-11-24 19:17
After updating to spring-boot 3.2.0
At initialisation getting  of
def wireMockServer = new WireMockServer(new WireMockConfiguration().dynamicPort())
Getting error
```
java.lang.IncompatibleClassChangeError: class org.eclipse.jetty.http2.server.HttpChannelOverHTTP2 has interface org.eclipse.jetty.server.HttpChannel as super class
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.<init>(AbstractHTTP2ServerConnectionFactory.java:82)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory.<init>(HTTP2ServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:48)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.createHttpConnector(Jetty11HttpServer.java:53)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.<init>(JettyHttpServer.java:89)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.<init>(Jetty11HttpServer.java:44)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServerFactory.buildHttpServer(JettyHttpServerFactory.java:31)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:81)
	at com.rewedigital.pushnotificationadapter.WireMockContextInitializer.initialize(WireMockContextInitializer.groovy:14)
```

**Comment by ComputerDaddyGuy** [comment] 2023-11-27 09:45
Hello,

Same error after having trying to upgrade to Spring Boot 3.2.0:

```
java.lang.IncompatibleClassChangeError: class org.eclipse.jetty.http2.server.HttpChannelOverHTTP2 has interface org.eclipse.jetty.server.HttpChannel as super class
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.<init>(AbstractHTTP2ServerConnectionFactory.java:82)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory.<init>(HTTP2ServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:48)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.createHttpConnector(Jetty11HttpServer.java:53)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.<init>(JettyHttpServer.java:89)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.<init>(Jetty11HttpServer.java:44)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServerFactory.buildHttpServer(JettyHttpServerFactory.java:31)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:81)
	at com.github.tomakehurst.wiremock.junit5.WireMockExtension.startServerIfRequired(WireMockExtension.java:164)
	at com.github.tomakehurst.wiremock.junit5.WireMockExtension.beforeAll(WireMockExtension.java:230)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: java.lang.NullPointerException: Cannot invoke "com.github.tomakehurst.wiremock.WireMockServer.isRunning()" because "this.wireMockServer" is null
		at com.github.tomakehurst.wiremock.junit5.WireMockExtension.stopServerIfRunning(WireMockExtension.java:218)
		at com.github.tomakehurst.wiremock.junit5.WireMockExtension.afterAll(WireMockExtension.java:256)
		... 1 more
```

Spring Boot 3.2.0 references `Jetty 12.0.3`, and Wiremock 3.3.1 references `Jetty 11.0.18`.

In Jetty 11, `org.eclipse.jetty.server.HttpChannel` was an [abstract class](https://github.com/jetty/jetty.project/blob/jetty-11.0.18/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java) whereas in Jetty 12 it is now an [interface](https://github.com/jetty/jetty.project/blob/jetty-12.0.3/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java).

**Comment by grkarolis** [comment] 2023-11-27 13:34
Hi, I am getting the same issue with Spring Boot `3.2.0` and Wiremock `3.3.1`.
As stated above using standalone is fine but would be appreciated if this issue is resolved moving forward.

**Comment by ThomasKasene** [comment] 2023-11-28 06:40
Can confirm. In my case I was able to work around it by downgrading Jetty _since my application uses Tomcat instead of Jetty_:

```xml
    <properties>
        <jetty.version>11.0.18</jetty.version>
        <wiremock.version>3.3.1</wiremock.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-bom</artifactId>
                <version>12.0.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by JohanNordlinder** [comment] 2023-12-14 11:46
> ### Workaround
> As a workaround, we can replace the wiremock package by the standalone one ( **org.wiremock:wiremock-standalone** ) so this is not an absolute blocker.

This is a great workaround, it also aligns well with the recommendation for Spring Boot users at https://masonm.github.io/wiremock/docs/getting-started/:
> Currently it is recommended that you use the standalone JAR as a dependency with Spring Boot projects. This avoids a conflict over the Jetty version

**Comment by ksiczek** [comment] 2023-12-14 11:56
One thing I noticed when migrating to `wiremock-standalone` was that its object mapper somehow started ignoring the `@JsonProperty` (some snake-case mapping) when doing `ResponseDefinitionBuilder .okForJson()`. I switched to the `okForContentType` with a string body but it was tricky to figure out. Other than that there were no issues.

**Comment by reta** [comment] 2024-01-11 18:31
@tomakehurst do you think it is viable to update to Jetty 12 in next major Wiremock release line (4.x I assume)? Happy to help there but curious what do you think since maintenance load definitely adds up.

**Comment by tomakehurst** [comment] 2024-01-12 14:12
I'd actually like to get it into 3.x but dynamically detecting the appropriate version (much like we did for Jetty 9.2/9.4 for quite a while) so that WireMock can co-habit with both.

I'm not going to get a chance to work on this immediately but happy to lend support if you'd like to try it this way.

**Comment by mschout** [comment] 2024-01-12 14:37
For me, switching to `-standalone` was all I needed to do FWIW.

**Comment by reta** [comment] 2024-01-12 14:49
> I'm not going to get a chance to work on this immediately but happy to lend support if you'd like to try it this way.

Sure, I will try to pick it up (happy to be assigned to the issue), thank you!

**Comment by mikebell90** [comment] 2024-01-24 18:54
Jetty 11 is now EOL, so Jetty 12 support is needed.

**Comment by BobbyRollof** [comment] 2024-02-12 09:02
Hi there!

Just out of curiosity, because I don't want to rush anyone who's doing good work. But could you tell me if there is an ETA for this change?

I ask because my team is anxiously waiting for this (well, I'm at least), since the wiremock-standalone route is not an optimal route for us.

I thank you for any info you can give me and thank you for the work you're doing.

**Comment by reta** [comment] 2024-04-02 17:12
@tomakehurst I think we could close this one, the documentation (with limitations) has been merged, thank you!

**Comment by tomakehurst** [comment] 2024-04-02 20:03
Jetty 12 supported from WireMock 3.5.2:
https://wiremock.org/docs/jetty-12/

Thanks @reta!

**Closed by tomakehurst** 2024-04-02 20:03 UTC
Labels: enhancement
