### ISSUE TITLE
EqualsToJson has bad performance for big json with common keys occuring often

### ISSUE THREAD

**Issue by dongelci** [wiremock/wiremock#2705] opened 2024-05-03 22:08 UTC
### Description

We have a test setup with recording via proxing in wiremock. Wiremock saves the mappings with equalsToJson pattern. 
After upgrading equalsToJson to JsonUnit there is a performance issue for a case. If there are many mappings with big json pattern having many keys in common, then response takes very long time, 40s to 55s. I forked the project and pushed acceptance test in branch gh-2705, see References

This happens only with many keys in common. If keys differ in every mapping, then there is no trouble. 

When I revert equalsToJson pattern to previous library, there is no issue, response takes a few seconds. 

Since I am not familiar with code base, I couldnt provide a fix in pull request but just acceptance test to reproduce.

### Proposal

Old library zjson compares under 1s. The same performance is required.

Timeout value, fixtures or accepysnce value can be refactored according to codin guidelines of wiremock project.

Values and keys in jsons have no meaning due to randomizing the values. You can gladly use own json but using same depth and amount of keys is important.

### Reproduction steps

Please run acceptance test to reproduce the error, see References or commit 0e6d6e2.

### References
https://github.com/dongelci/wiremock/tree/gh-2705

**Comment by leeturner** [comment] 2024-05-21 11:54
Hi, many thanks for taking the time to fork the project and add the test.  It is very helpful.  Would it be possible to let us know if you are upgrading from one version of WireMock to another where you saw the performance issue so we can try and narrow down where the performance regression might be. 

You also mentioned `zjson` in your issue report.  Could you give more information on what `zjson` is

**Comment by dongelci** [comment] 2024-05-21 19:18
Hi @leeturner, 

thanks for your feedback.

I mean zjsonpatch. This is a library used before switching to jsonunit. Relevant commit is 7ead912, which was reverted in 
ef4cf34 and then reused in 28c5e67. 

2.27.2 has no issue. Next release after this is 3.0.0 and there is an issue in it

**Comment by tomakehurst** [comment] 2024-05-22 09:00
We switched away from zjsonpatch partly because there were comparison bugs we couldn't resolve with it IIRC.

Since we're dependent on JsonUnit now and the performance issue is presumably within its diff code, maybe it would make sense to raise an issue with that project?

Also, generally I wouldn't recommend using `equalToJson` for large comparisons. `matchesJsonPath` is usually much more efficient here, particularly since we introduced some per-request caching that's most effective when you use sub-matchers.

**Comment by dongelci** [comment] 2024-06-05 09:45
Hi @tomakehurst ,

Sorry for late reply. 

I also suspect diff creation. I would open an issue at `JsonUnit` but needed to discuss other options with you.

We are using recording feature with persistent stubs. We could write a Transformer maybe but I am afraid json is too dynamic to define a concrete attribute to use `matchesJsonPath` but I will take into consideration.

I will inform, when I open an issue at `JsonUnit`

**Comment by dongelci** [comment] 2024-06-26 14:04
I created an issue at `JsonUnit`. 
https://github.com/lukas-krecan/JsonUnit/issues/782

**Comment by lukas-krecan** [comment] 2024-06-27 04:50
Hi, I did some performance optimizations in JsoUnit 3.3.0 (just released) so it should be better

**Comment by leeturner** [comment] 2024-06-27 07:56
Awesome, thank you for the update.  We will take a look and see if we can upgrade

**Comment by leeturner** [comment] 2024-07-01 17:04
Looks like we will have to pick this up when we no longer need to support java 11

**Comment by lukas-krecan** [comment] 2024-07-01 17:29
If you want, I can backport it to the 4.x.x branch

**Comment by lukas-krecan** [comment] 2024-07-01 18:00
I just released 2.39.0 with the changes backported

**Comment by leeturner** [comment] 2024-07-01 20:17
That is amazing. Thank you.

**Comment by leeturner** [comment] 2024-07-02 09:25
This update has now been merged and will be released in the next version of WireMock.  Many thanks to @dongelci for reporting and @lukas-krecan for fixing and back porting 🙏

**Closed by leeturner** 2024-07-02 09:25 UTC
Labels: bug

**Comment by tomakehurst** [comment] 2024-07-02 10:48
@lukas-krecan thanks from me also for backporting this! This will save us a huge amount of work in the short/mid term.

**Comment by lukas-krecan** [comment] 2024-07-02 14:25
You are welcome. Btw. if wiremock only needs to know if JSONs are equivalent but it does not need to know all the differences, we may optimize it even further (if necessary).

**Comment by tomakehurst** [comment] 2024-07-03 08:26
Yes - most of the time all WireMock needs to know is whether a difference exists, so anything that's optimised to return false as soon as a difference is found would probably yield a pretty large performance gain.

**Comment by lukas-krecan** [comment] 2024-07-03 18:22
I have just released JsonUnit 2.40.0 (and 3.4.0) - if you specify `FAIL_FAST` option, the comparison stops at the first difference.

**Comment by tomakehurst** [comment] 2024-07-03 21:18
This is truly great stuff - thanks again!

**Comment by leeturner** [comment] 2024-07-04 08:45
Awesome, thank you
